//
// Created by Avihoo on 13/06/2020.
//

#ifndef TETRIS_TETRIS_H
#define TETRIS_TETRIS_H

#define GAME_GRID_WIDTH 10
#define GAME_GRID_HEIGHT 24
#define GAME_GRID_INVISIBLE_LINES 0

#define MILLISECONDS_PER_TICK 10

#define MAIN_FRAME_LEFT 2
#define MAIN_FRAME_TOP 2
#define MAIN_FRAME_WIDTH GAME_GRID_WIDTH + 2
#define MAIN_FRAME_HEIGHT GAME_GRID_HEIGHT + 2

#define WINDOW_WIDTH 22
#define WINDOW_HEIGHT 30

#endif //TETRIS_TETRIS_H
