//
// Created by Avihoo on 13/06/2020.
//

#ifndef TETRIS_TETRIS_H
#define TETRIS_TETRIS_H

#define GAME_GRID_WIDTH 10
#define GAME_GRID_HEIGHT 26
#define GAME_GRID_INVISIBLE_LINES 2

#define MILLISECONDS_PER_TICK 5

#define MAIN_FRAME_LEFT 2
#define MAIN_FRAME_TOP 2
#define MAIN_FRAME_WIDTH (GAME_GRID_WIDTH + 2)
#define MAIN_FRAME_HEIGHT (GAME_GRID_HEIGHT + 2 - GAME_GRID_INVISIBLE_LINES)

#define ENQUEUED_FRAME_LEFT (MAIN_FRAME_LEFT + MAIN_FRAME_WIDTH + 2)
#define ENQUEUED_FRAME_TOP ((MAIN_FRAME_TOP + MAIN_FRAME_HEIGHT) / 2)

#define SCORE_TEXT_LEFT (MAIN_FRAME_LEFT + MAIN_FRAME_WIDTH + 1)
#define SCORE_TEXT_TOP (((MAIN_FRAME_TOP + MAIN_FRAME_HEIGHT) * 2) / 11)

#define LEVEL_TEXT_LEFT ((MAIN_FRAME_LEFT + MAIN_FRAME_WIDTH) / 2)
#define LEVEL_TEXT_TOP MAIN_FRAME_TOP

#define LINES_REMAINING_TEXT_LEFT SCORE_TEXT_LEFT
#define LINES_REMAINING_TEXT_TOP (SCORE_TEXT_TOP + 2)

#define WINDOW_WIDTH (MAIN_FRAME_WIDTH + 16)
#define WINDOW_HEIGHT (MAIN_FRAME_HEIGHT + 4)

#endif //TETRIS_TETRIS_H
